### ISSUE TITLE
Show total metrics and time stored per tier

### ISSUE THREAD

**Issue by Forza-tng** [netdata/netdata-storage-calculator#2]
Hi,

Thanks for the calculator. Makes it easier to calculate storage needs. I see something that could improve it. To, me it is important to understand how long (days/hours) i can store metrics per chosen resolution. Currently this is not possible as the calculator only show the retention time for the 3rd tier as can be seen from the screenshot:
![image](https://user-images.githubusercontent.com/68693597/210769969-68de69f1-5f15-4296-b5f8-85d39fb13005.png)

Would it be possible to add a calculation per tier column that contains `metrics` and `hours / days of retention`?

I did a simple change in the Python code which could be sufficient:

```python
output_message += f'for a maximum of **{round(metric_retention_days_tier_0):000,} days (T0)**, **{round(metric_retention_days_tier_1):000,} days (T1)**, **{round(metric_retention_days_tier_2):000,} days (T2)** utilizing **{round(estimated_disk_storage_gb,2):000,} GB** of disk storage '
```

This results in this output:

_Netdata will store an estimated 19,597,885,440 data points (979,894 points/metric) for a maximum of 7 days (T0), 365 days (T1), 1,847 days (T2) utilizing 60.35 GB of disk storage and 3,764 MB of RAM._

**Comment by andrewm4894** [comment]
thanks @Forza-tng 

i know @netdata/agent team are planning on updating the calculator once some ongoing work around the dbengine is finalized - will make sure they get this feedback.

feel free to make a PR in meantime if you want as i think change you suggest seems straightforward.

**Comment by andrewm4894** [comment]
actually ill have a quick go at this in here myself - keep to see if can just use a github codespace to do it https://github.com/netdata/netdata-storage-calculator/tree/update-output-message

**Comment by andrewm4894** [comment]
#4
